create database Campeonato;
use Campeonato;
create table Equipos(
codigo_pais char(3) primary key,
nombre_pais varchar(40) not null,
codigo_confederacion char(10) not null
);

create table paisescod(
codigo_pais char(3) primary key,
nombre_pais varchar(40) not null,
);

create table paisesconf(
nombre_pais varchar(40) primary key,
codigo_confederacion char(10) not null
);

insert into paisescod(nombre_pais,codigo_pais)
values('Afganistán','AFG'),
('Albania','ALB'),
('Alemania','GER'),
('Andorra','AND'),
('Angola','ANG'),
('Anguila','AIA'),
('Antigua y Barbuda','ATG'),
('Arabia Saudita','KSA'),
('Argelia','ALG'),
('Argentina','ARG'),
('Armenia','ARM'),
('Aruba','ARU'),
('Australia','AUS'),
('Austria','AUT'),
('Azerbaiyán','AZE'),
('Bahamas','BAH'),
('Bangladés','BAN'),
('Barbados','BRB'),
('Baréin','BHR'),
('Bélgica','BEL'),
('Belice','BLZ'),
('Benín','BEN'),
('Bermudas','BER'),
('Bielorrusia','BLR'),
('Birmania','MYA'),
('Bolivia','BOL'),
('Bosnia y Herzegovina','BIH'),
('Botsuana','BOT'),
('Brasil','BRA'),
('Brunéi','BRU'),
('Bulgaria','BUL'),
('Burkina Faso','BFA'),
('Burundi','BDI'),
('Bután','BHU'),
('Cabo Verde','CPV'),
('Camboya','CAM'),
('Camerún','CMR'),
('Canadá','CAN'),
('Catar','QAT'),
('Chad','CHA'),
('Chile','CHI'),
('China','CHN'),
('China Taipéi','TPE'),
('Chipre','CYP'),
('Colombia','COL'),
('Comoras','COM'),
('Corea del Norte','PRK'),
('Corea del Sur','KOR'),
('Costa de Marfil','CIV'),
('Costa Rica','CRC'),
('Croacia','CRO'),
('Cuba','CUB'),
('Curazao','CUW'),
('Dinamarca','DEN'),
('Dominica','DMA'),
('Ecuador','ECU'),
('Egipto','EGY'),
('El Salvador','SLV'),
('Emiratos Árabes Unidos','UAE'),
('Eritrea','ERI'),
('Escocia','SCO'),
('Eslovaquia','SVK'),
('Eslovenia','SVN'),
('España','ESP'),
('Estados Unidos','USA'),
('Estonia','EST'),
('Etiopía','ETH'),
('Filipinas','PHI'),
('Finlandia','FIN'),
('Fiyi','FIJ'),
('Francia','FRA'),
('Gabón','GAB'),
('Gales','WAL'),
('Gambia','GAM'),
('Georgia','GEO'),
('Ghana','GHA'),
('Gibraltar','GIB'),
('Granada','GRN'),
('Grecia','GRE'),
('Guam','GUM'),
('Guatemala','GUA'),
('Guinea','GUI'),
('Guinea-Bisáu','GNB'),
('Guinea Ecuatorial','EQG'),
('Guyana','GUY'),
('Haití','HAI'),
('Honduras','HON'),
('Hong Kong','HKG'),
('Hungría','HUN'),
('India','IND'),
('Indonesia','IDN'),
('Inglaterra','ENG'),
('Irak','IRQ'),
('Irán','IRN'),
('Irlanda','IRL'),
('Irlanda del Norte','NIR'),
('Islandia','ISL'),
('Islas Caimán','CAY'),
('Islas Cook','COK'),
('Islas Feroe','FRO'),
('Islas Salomón','SOL'),
('Islas Turcas y Caicos','TCA'),
('Islas Vírgenes Británicas','VGB'),
('Islas Vírgenes Estadounidenses','VIR'),
('Israel','ISR'),
('Italia','ITA'),
('Jamaica','JAM'),
('Japón','JPN'),
('Jordania','JOR'),
('Kazajistán','KAZ'),
('Kenia','KEN'),
('Kirguistán','KGZ'),
('Kosovo','KVX'),
('Kuwait','KUW'),
('Laos','LAO'),
('Lesoto','LES'),
('Letonia','LVA'),
('Líbano','LIB'),
('Liberia','LBR'),
('Libia','LBY'),
('Liechtenstein','LIE'),
('Lituania','LTU'),
('Luxemburgo','LUX'),
('Macao','MAC'),
('Macedonia','MKD'),
('Madagascar','MAD'),
('Malasia','MAS'),
('Malaui','MWI'),
('Maldivas','MDV'),
('Malí','MLI'),
('Malta','MLT'),
('Marruecos','MAR'),
('Mauricio','MRI'),
('Mauritania','MTN'),
('México','MEX'),
('Moldavia','MDA'),
('Mongolia','MNG'),
('Montenegro','MNE'),
('Montserrat','MSR'),
('Mozambique','MOZ'),
('Namibia','NAM'),
('Nepal','NEP'),
('Nicaragua','NCA'),
('Níger','NIG'),
('Nigeria','NGA'),
('Noruega','NOR'),
('Nueva Caledonia','NCL'),
('Nueva Zelanda','NZL'),
('Omán','OMA'),
('Países Bajos','NED'),
('Pakistán','PAK'),
('Palestina','PLE'),
('Panamá','PAN'),
('Papúa Nueva Guinea','PNG'),
('Paraguay','PAR'),
('Perú','PER'),
('Polonia','POL'),
('Portugal','POR'),
('Puerto Rico','PUR'),
('República Centroafricana','CTA'),
('República Checa','CZE'),
('República del Congo','CGO'),
('República Democrática del Congo','COD'),
('República Dominicana','DOM'),
('Ruanda','RWA'),
('Rumania','ROU'),
('Rusia','RUS'),
('Samoa','SAM'),
('Samoa Americana','ASA'),
('San Cristóbal y Nieves','SKN'),
('San Marino','SMR'),
('San Vicente y las Granadinas','VIN'),
('Santa Lucía','LCA'),
('Santo Tomé y Príncipe','STP'),
('Senegal','SEN'),
('Serbia','SRB'),
('Seychelles','SEY'),
('Sierra Leona','SLE'),
('Singapur','SIN'),
('Siria','SYR'),
('Somalia','SOM'),
('Sri Lanka','SRI'),
('Suazilandia','SWZ'),
('Sudáfrica','RSA'),
('Sudán','SDN'),
('Sudán del Sur','SSD'),
('Suecia','SWE'),
('Suiza','SUI'),
('Surinam','SUR'),
('Tahití','TAH'),
('Tanzania','TAN'),
('Tayikistán','TJK'),
('Timor Oriental','TLS'),
('Togo','TOG'),
('Tonga','TGA'),
('Trinidad y Tobago','TRI'),
('Túnez','TUN'),
('Turkmenistán','TKM'),
('Turquía','TUR'),
('Ucrania','UKR'),
('Uganda','UGA'),
('Uruguay','URU'),
('Uzbekistán','UZB'),
('Vanuatu','VAN'),
('Venezuela','VEN'),
('Vietnam','VIE'),
('Yemen','YEM'),
('Yibuti','DJI'),
('Zambia','ZAM'),
('Zimbabue','ZIM')
;

insert into paisesconf(nombre_pais,codigo_confederacion)
values('Afganistán','AFC'),
('Arabia Saudí','AFC'),
('Australia','AFC'),
('Bahréin','AFC'),
('Bangladesh','AFC'),
('Brunéi Darussalam','AFC'),
('Bután','AFC'),
('Camboya','AFC'),
('Chinese Taipei','AFC'),
('Emiratos Árabes Unidos','AFC'),
('Filipinas','AFC'),
('Guam','AFC'),
('Hong Kong','AFC'),
('India','AFC'),
('Indonesia','AFC'),
('Irak','AFC'),
('Irán','AFC'),
('Japón','AFC'),
('Jordania','AFC'),
('Kuwait','AFC'),
('Laos','AFC'),
('Líbano','AFC'),
('Macao','AFC'),
('Malasia','AFC'),
('Maldivas','AFC'),
('Mongolia','AFC'),
('Myanmar','AFC'),
('Nepal','AFC'),
('Omán','AFC'),
('Pakistán','AFC'),
('Palestina','AFC'),
('Qatar','AFC'),
('RDP de Corea','AFC'),
('República de Corea','AFC'),
('República Kirguisa','AFC'),
('RP China','AFC'),
('Singapur','AFC'),
('Siria','AFC'),
('Sri Lanka','AFC'),
('Tailandia','AFC'),
('Tayikistán','AFC'),
('Timor Oriental','AFC'),
('Turkmenistán','AFC'),
('Uzbekistán','AFC'),
('Vietnam','AFC'),
('Yemen','AFC'),
('Angola','CAF'),
('Argelia','CAF'),
('Benín','CAF'),
('Botsuana','CAF'),
('Burkina Faso','CAF'),
('Burundi','CAF'),
('Cabo Verde','CAF'),
('Camerún','CAF'),
('Chad','CAF'),
('Comoras','CAF'),
('Congo','CAF'),
('Costa de Marfil','CAF'),
('Egipto','CAF'),
('Eritrea','CAF'),
('Etiopía','CAF'),
('Gabón','CAF'),
('Gambia','CAF'),
('Ghana','CAF'),
('Guinea','CAF'),
('Guinea Ecuatorial','CAF'),
('Guinea-Bissáu','CAF'),
('Kenia','CAF'),
('Lesoto','CAF'),
('Liberia','CAF'),
('Libia','CAF'),
('Madagascar','CAF'),
('Malaui','CAF'),
('Mali','CAF'),
('Marruecos','CAF'),
('Mauricio','CAF'),
('Mauritania','CAF'),
('Mozambique','CAF'),
('Namibia','CAF'),
('Níger','CAF'),
('Nigeria','CAF'),
('RD del Congo','CAF'),
('República Centroafricana','CAF'),
('Ruanda','CAF'),
('Santo Tomé y Príncipe','CAF'),
('Senegal','CAF'),
('Seychelles','CAF'),
('Sierra Leona','CAF'),
('Somalia','CAF'),
('Suazilandia','CAF'),
('Sudáfrica','CAF'),
('Sudán','CAF'),
('Sudán del Sur','CAF'),
('Tanzania','CAF'),
('Togo','CAF'),
('Túnez','CAF'),
('Uganda','CAF'),
('Yibuti','CAF'),
('Zambia','CAF'),
('Zimbabue','CAF'),
('Anguila','CONCACAF'),
('Antigua y Barbuda','CONCACAF'),
('Aruba','CONCACAF'),
('Bahamas','CONCACAF'),
('Barbados','CONCACAF'),
('Belice','CONCACAF'),
('Bermudas','CONCACAF'),
('Canadá','CONCACAF'),
('Costa Rica','CONCACAF'),
('Cuba','CONCACAF'),
('Curazao','CONCACAF'),
('Dominica','CONCACAF'),
('EEUU','CONCACAF'),
('El Salvador','CONCACAF'),
('Granada','CONCACAF'),
('Guatemala','CONCACAF'),
('Guyana','CONCACAF'),
('Haití','CONCACAF'),
('Honduras','CONCACAF'),
('Islas Caimán','CONCACAF'),
('Islas Vírgenes Británicas','CONCACAF'),
('Islas Vírgenes Estadounidenses','CONCACAF'),
('Jamaica','CONCACAF'),
('México','CONCACAF'),
('Montserrat','CONCACAF'),
('Nicaragua','CONCACAF'),
('Panamá','CONCACAF'),
('Puerto Rico','CONCACAF'),
('República Dominicana','CONCACAF'),
('San Cristóbal y Nieves','CONCACAF'),
('San Vicente y las Granadinas','CONCACAF'),
('Santa Lucía','CONCACAF'),
('Surinam','CONCACAF'),
('Trinidad y Tobago','CONCACAF'),
('Turcas y Caicos','CONCACAF'),
('Argentina','CONMEBOL'),
('Bolivia','CONMEBOL'),
('Brasil','CONMEBOL'),
('Chile','CONMEBOL'),
('Colombia','CONMEBOL'),
('Ecuador','CONMEBOL'),
('Paraguay','CONMEBOL'),
('Perú','CONMEBOL'),
('Uruguay','CONMEBOL'),
('Venezuela','CONMEBOL'),
('Fiyi','OFC'),
('Islas Cook','OFC'),
('Islas Salomón','OFC'),
('Nueva Caledonia','OFC'),
('Nueva Zelanda','OFC'),
('Papúa Nueva Guinea','OFC'),
('Samoa','OFC'),
('Samoa Estadounidense','OFC'),
('Tahití','OFC'),
('Tonga','OFC'),
('Vanuatu','OFC'),
('Albania','UEFA'),
('Alemania','UEFA'),
('Andorra','UEFA'),
('Armenia','UEFA'),
('ARY de Macedonia','UEFA'),
('Austria','UEFA'),
('Azerbaiyán','UEFA'),
('Bélgica','UEFA'),
('Bielorrusia','UEFA'),
('Bosnia y Herzegovina','UEFA'),
('Bulgaria','UEFA'),
('Chipre','UEFA'),
('Croacia','UEFA'),
('Dinamarca','UEFA'),
('Escocia','UEFA'),
('Eslovaquia','UEFA'),
('Eslovenia','UEFA'),
('España','UEFA'),
('Estonia','UEFA'),
('Finlandia','UEFA'),
('Francia','UEFA'),
('Gales','UEFA'),
('Georgia','UEFA'),
('Gibraltar','UEFA'),
('Grecia','UEFA'),
('Hungría','UEFA'),
('Inglaterra','UEFA'),
('Irlanda del Norte','UEFA'),
('Islandia','UEFA'),
('Islas Feroe','UEFA'),
('Israel','UEFA'),
('Italia','UEFA'),
('Kazajstán','UEFA'),
('Kosovo','UEFA'),
('Letonia','UEFA'),
('Liechtenstein','UEFA'),
('Lituania','UEFA'),
('Luxemburgo','UEFA'),
('Malta','UEFA'),
('Moldavia','UEFA'),
('Montenegro','UEFA'),
('Noruega','UEFA'),
('Países Bajos','UEFA'),
('Polonia','UEFA'),
('Portugal','UEFA'),
('República Checa','UEFA'),
('República de Irlanda','UEFA'),
('Rumanía','UEFA'),
('Rusia','UEFA'),
('San Marino','UEFA'),
('Serbia','UEFA'),
('Suecia','UEFA'),
('Suiza','UEFA'),
('Turquía','UEFA'),
('Ucrania','UEFA')
;

insert into Equipos
select top 6 codigo_pais,paisescod.nombre_pais,codigo_confederacion from paisescod join paisesconf on paisescod.nombre_pais=paisesconf.nombre_pais and  codigo_confederacion = 'CONCACAF'
union
select top 5 codigo_pais,paisescod.nombre_pais,codigo_confederacion from paisescod join paisesconf on paisescod.nombre_pais=paisesconf.nombre_pais and  codigo_confederacion = 'CONMEBOL'
union
select top 6 codigo_pais,paisescod.nombre_pais,codigo_confederacion from paisescod join paisesconf on paisescod.nombre_pais=paisesconf.nombre_pais and  codigo_confederacion = 'UEFA'
union
select top 5 codigo_pais,paisescod.nombre_pais,codigo_confederacion from paisescod join paisesconf on paisescod.nombre_pais=paisesconf.nombre_pais and  codigo_confederacion = 'CAF'
union
select top 5 codigo_pais,paisescod.nombre_pais,codigo_confederacion from paisescod join paisesconf on paisescod.nombre_pais=paisesconf.nombre_pais and  codigo_confederacion = 'AFC'
union
select top 5 codigo_pais,paisescod.nombre_pais,codigo_confederacion from paisescod join paisesconf on paisescod.nombre_pais=paisesconf.nombre_pais and  codigo_confederacion = 'OFC'
;

select * from Equipos;