--Fallo de inserción en las filas  1  mediante  32 
--ORA-12899: value too large for column "DVALVERDEADMIN"."EQUIPO"."COD_PAIS" (actual: 6, maximum: 3)
--Fila 1
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('AFG','Afganistán','AFC');
--Fila 2
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('AIA','Anguila','CONCACAF');
--Fila 3
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('ALB','Albania','UEFA');
--Fila 4
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('ALG','Argelia','CAF');
--Fila 5
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('AND','Andorra','UEFA');
--Fila 6
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('ANG','Angola','CAF');
--Fila 7
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('ARG','Argentina','CONMEBOL');
--Fila 8
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('ARM','Armenia','UEFA');
--Fila 9
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('ARU','Aruba','CONCACAF');
--Fila 10
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('ATG','Antigua y Barbuda','CONCACAF');
--Fila 11
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('AUS','Australia','AFC');
--Fila 12
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('AUT','Austria','UEFA');
--Fila 13
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('AZE','Azerbaiyán','UEFA');
--Fila 14
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('BAH','Bahamas','CONCACAF');
--Fila 15
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('BDI','Burundi','CAF');
--Fila 16
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('BEL','Bélgica','UEFA');
--Fila 17
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('BEN','Benín','CAF');
--Fila 18
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('BER','Bermudas','CONCACAF');
--Fila 19
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('BFA','Burkina Faso','CAF');
--Fila 20
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('BHU','Bután','AFC');
--Fila 21
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('BLZ','Belice','CONCACAF');
--Fila 22
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('BOL','Bolivia','CONMEBOL');
--Fila 23
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('BRA','Brasil','CONMEBOL');
--Fila 24
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('CAM','Camboya','AFC');
--Fila 25
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('CHI','Chile','CONMEBOL');
--Fila 26
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('COK','Islas Cook','OFC');
--Fila 27
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('COL','Colombia','CONMEBOL');
--Fila 28
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('FIJ','Fiyi','OFC');
--Fila 29
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('GUM','Guam','AFC');
--Fila 30
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('NCL','Nueva Caledonia','OFC');
--Fila 31
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('NZL','Nueva Zelanda','OFC');
--Fila 32
INSERT INTO EQUIPO (COD_PAIS, NOMBRE_PAIS, COD_CONFEDERACION) VALUES ('SOL','Islas Salomón','OFC');
